export type CountryCatalogEntry = {
  key: string;
  label: string;
  code: string;
  globeName: string;
  flag: string;
  region: string;
  aliases: string[];
};

export const countryCatalog: CountryCatalogEntry[] = [
  {
    key: 'USA',
    label: 'USA',
    code: 'US',
    globeName: 'United States of America',
    flag: 'US',
    region: 'North America',
    aliases: ['usa', 'us', 'united states', 'united states of america'],
  },
  {
    key: 'UK',
    label: 'UK',
    code: 'GB',
    globeName: 'United Kingdom',
    flag: 'UK',
    region: 'Europe',
    aliases: ['uk', 'gb', 'great britain', 'united kingdom'],
  },
  {
    key: 'France',
    label: 'France',
    code: 'FR',
    globeName: 'France',
    flag: 'FR',
    region: 'Europe',
    aliases: ['france'],
  },
  {
    key: 'Germany',
    label: 'Germany',
    code: 'DE',
    globeName: 'Germany',
    flag: 'DE',
    region: 'Europe',
    aliases: ['germany'],
  },
  {
    key: 'Italy',
    label: 'Italy',
    code: 'IT',
    globeName: 'Italy',
    flag: 'IT',
    region: 'Europe',
    aliases: ['italy'],
  },
  {
    key: 'Spain',
    label: 'Spain',
    code: 'ES',
    globeName: 'Spain',
    flag: 'ES',
    region: 'Europe',
    aliases: ['spain'],
  },
  {
    key: 'Japan',
    label: 'Japan',
    code: 'JP',
    globeName: 'Japan',
    flag: 'JP',
    region: 'Asia',
    aliases: ['japan'],
  },
  {
    key: 'South Korea',
    label: 'South Korea',
    code: 'KR',
    globeName: 'South Korea',
    flag: 'KR',
    region: 'Asia',
    aliases: ['south korea', 'korea, republic of', 'republic of korea'],
  },
  {
    key: 'China',
    label: 'China',
    code: 'CN',
    globeName: 'China',
    flag: 'CN',
    region: 'Asia',
    aliases: ['china'],
  },
  {
    key: 'India',
    label: 'India',
    code: 'IN',
    globeName: 'India',
    flag: 'IN',
    region: 'Asia',
    aliases: ['india'],
  },
  {
    key: 'Brazil',
    label: 'Brazil',
    code: 'BR',
    globeName: 'Brazil',
    flag: 'BR',
    region: 'South America',
    aliases: ['brazil'],
  },
  {
    key: 'Argentina',
    label: 'Argentina',
    code: 'AR',
    globeName: 'Argentina',
    flag: 'AR',
    region: 'South America',
    aliases: ['argentina'],
  },
  {
    key: 'Mexico',
    label: 'Mexico',
    code: 'MX',
    globeName: 'Mexico',
    flag: 'MX',
    region: 'North America',
    aliases: ['mexico'],
  },
  {
    key: 'Canada',
    label: 'Canada',
    code: 'CA',
    globeName: 'Canada',
    flag: 'CA',
    region: 'North America',
    aliases: ['canada'],
  },
  {
    key: 'Australia',
    label: 'Australia',
    code: 'AU',
    globeName: 'Australia',
    flag: 'AU',
    region: 'Oceania',
    aliases: ['australia'],
  },
  {
    key: 'New Zealand',
    label: 'New Zealand',
    code: 'NZ',
    globeName: 'New Zealand',
    flag: 'NZ',
    region: 'Oceania',
    aliases: ['new zealand'],
  },
  {
    key: 'Ireland',
    label: 'Ireland',
    code: 'IE',
    globeName: 'Ireland',
    flag: 'IE',
    region: 'Europe',
    aliases: ['ireland'],
  },
  {
    key: 'Denmark',
    label: 'Denmark',
    code: 'DK',
    globeName: 'Denmark',
    flag: 'DK',
    region: 'Europe',
    aliases: ['denmark'],
  },
  {
    key: 'Sweden',
    label: 'Sweden',
    code: 'SE',
    globeName: 'Sweden',
    flag: 'SE',
    region: 'Europe',
    aliases: ['sweden'],
  },
  {
    key: 'Norway',
    label: 'Norway',
    code: 'NO',
    globeName: 'Norway',
    flag: 'NO',
    region: 'Europe',
    aliases: ['norway'],
  },
  {
    key: 'Poland',
    label: 'Poland',
    code: 'PL',
    globeName: 'Poland',
    flag: 'PL',
    region: 'Europe',
    aliases: ['poland'],
  },
  {
    key: 'Netherlands',
    label: 'Netherlands',
    code: 'NL',
    globeName: 'Netherlands',
    flag: 'NL',
    region: 'Europe',
    aliases: ['netherlands', 'holland'],
  },
  {
    key: 'Belgium',
    label: 'Belgium',
    code: 'BE',
    globeName: 'Belgium',
    flag: 'BE',
    region: 'Europe',
    aliases: ['belgium'],
  },
  {
    key: 'Austria',
    label: 'Austria',
    code: 'AT',
    globeName: 'Austria',
    flag: 'AT',
    region: 'Europe',
    aliases: ['austria'],
  },
  {
    key: 'Portugal',
    label: 'Portugal',
    code: 'PT',
    globeName: 'Portugal',
    flag: 'PT',
    region: 'Europe',
    aliases: ['portugal'],
  },
  {
    key: 'Turkey',
    label: 'Turkey',
    code: 'TR',
    globeName: 'Turkey',
    flag: 'TR',
    region: 'Europe / Asia',
    aliases: ['turkey', 'turkiye'],
  },
  {
    key: 'Thailand',
    label: 'Thailand',
    code: 'TH',
    globeName: 'Thailand',
    flag: 'TH',
    region: 'Asia',
    aliases: ['thailand'],
  },
  {
    key: 'Nigeria',
    label: 'Nigeria',
    code: 'NG',
    globeName: 'Nigeria',
    flag: 'NG',
    region: 'Africa',
    aliases: ['nigeria'],
  },
  {
    key: 'South Africa',
    label: 'South Africa',
    code: 'ZA',
    globeName: 'South Africa',
    flag: 'ZA',
    region: 'Africa',
    aliases: ['south africa'],
  },
  {
    key: 'Egypt',
    label: 'Egypt',
    code: 'EG',
    globeName: 'Egypt',
    flag: 'EG',
    region: 'Africa',
    aliases: ['egypt'],
  },
];

export const countryCatalogByKey = new Map(countryCatalog.map((country) => [country.key, country] as const));
export const countryCatalogByGlobeName = new Map(
  countryCatalog.map((country) => [country.globeName, country] as const),
);
export const browseCountryOptions = countryCatalog.map((country) => ({
  label: country.label,
  code: country.code,
  aliases: country.aliases,
}));
export const browseCountries = browseCountryOptions.map((country) => country.label);
export const browseCountryCodeByLabel = Object.fromEntries(
  browseCountryOptions.map((country) => [country.label, country.code]),
) as Record<string, string>;

const browseCountryAliasMap = new Map(
  browseCountryOptions.flatMap((country) => country.aliases.map((alias) => [alias, country.label] as const)),
);

export function normalizeBrowseCountry(value: string) {
  const normalized = value.trim().toLowerCase();
  return browseCountryAliasMap.get(normalized) ?? value.trim();
}
